module.exports.CourseWorkType = {
	COURSE_WORK_TYPE_UNSPECIFIED: 'COURSE_WORK_TYPE_UNSPECIFIED',
	ASSIGNMENT: 'ASSIGNMENT',
	SHORT_ANSWER_QUESTION: 'SHORT_ANSWER_QUESTION',
	MULTIPLE_CHOICE_QUESTION: 'MULTIPLE_CHOICE_QUESTION',
};

module.exports.SubmissionState = {
	SUBMISSION_STATE_UNSPECIFIED: 'SUBMISSION_STATE_UNSPECIFIED',
	NEW: 'NEW',
	CREATED: 'CREATED',
	TURNED_IN: 'TURNED_IN',
	RETURNED: 'RETURNED',
	RECLAIMED_BY_STUDENT: 'RECLAIMED_BY_STUDENT',
};
